#!/usr/bin/env bash

true=0
false=1

export PS1="\u@\h: \w$ "

export LANG="ru_RU.UTF-8"
export LC_COLLATE="ru_RU.UTF-8"
export LC_CTYPE="ru_RU.UTF-8"
export LC_MESSAGES="ru_RU.UTF-8"
export LC_MONETARY="ru_RU.UTF-8"
export LC_NUMERIC="ru_RU.UTF-8"
export LC_TIME="ru_RU.UTF-8"
export LC_ALL=""

eval "$(/usr/local/bin/brew shellenv)"

source ~/.env-secrets
source ~/.git-completion.bash
#source ~/.make-completion.bash
#source ~/.fzf.bash

[ -s "/Users/20607157/.jabba/jabba.sh" ] && source "/Users/20607157/.jabba/jabba.sh"
[[ -r "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh" ]] && . "$HOMEBREW_PREFIX/etc/profile.d/bash_completion.sh"

fn_onkavd() {
  sudo "-v" && \
  if [[ $(sudo launchctl list) != *"com.kaspersky.kav.kavd"* ]]; then
    sudo launchctl load /Library/LaunchDaemons/com.kaspersky.kav.kavd.plist
  fi
}

fn_offkavd() {
  sudo "-v" && \
  if [[ $(sudo launchctl list) == *"com.kaspersky.kav.kavd"* ]]; then
    sudo launchctl kill -9 system/com.kaspersky.kav.kavd;
    sudo launchctl unload /Library/LaunchDaemons/com.kaspersky.kav.kavd.plist
  fi
}

tunnelblick_connect() {
  tunnelblick_disconnect; cisco_disconnect; \
  osascript -e "tell application \"/Applications/Tunnelblick.app\"" -e "connect \"$1\"" -e "end tell" \
  && oathtool --totp -b -d 6 $2 | tr -d "\n" | pbcopy \
  && osascript -e "tell application \"System Events\" to keystroke \"v\" using command down" \
  && osascript -e "tell application \"System Events\" to keystroke return"
}

tunnelblick_disconnect() {
  osascript -e "tell application \"Tunnelblick\"" -e "disconnect all" -e "end tell"
  sleep 3
}

cisco_is_connected() {
  if [[ $(ifconfig) == *"utun4"* ]]; then
    return $true
  fi
  return $false
}

cisco_connect() {
  if ! cisco_is_connected; then
    osascript ~/sber/dotfiles/osx/cisco.connect.AppleScript
  fi
}

cisco_disconnect() {
  if cisco_is_connected; then
    osascript ~/sber/dotfiles/osx/cisco.disconnect.AppleScript
  fi
}

alias oak='tunnelblick_connect "oak" $OAK_TOKEN'
alias cloud='tunnelblick_connect "cloud" $CLOUD_TOKEN'

alias sigma='tunnelblick_disconnect; cisco_connect'
alias offsigma='cisco_disconnect'

alias onkavd='fn_onkavd'
alias offkavd='fn_offkavd'

alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'

#export GOSUMDB=off
export GO111MODULE=on

export FZF_DEFAULT_COMMAND='vim $(fzf --height 70% --border)'

EXT_PATH=/Users/20607157/go/bin:/usr/local/include:/usr/local/opt/openssl@3/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/opt/make/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/grep/libexec/gnubin:/usr/local/opt/rsync/bin:/usr/local/opt/gradle@7/bin

export PATH=$EXT_PATH:$PATH
